#输入的视频文件
input: C:\Users\cai-x\Downloads\2023-12-08_14-27-30.mp4
#中间过程会生成的音频文件
output: C:\Users\cai-x\Downloads\2023-12-08_14-27-30.mp3
#生成的原始字幕文件
srt_path: C:\Users\cai-x\Downloads\2023-12-08_14-27-30.srt
#生成的翻译后的字幕文件
srt_translate_path: C:\Users\cai-x\Downloads\2023-12-08_14-27-30-zh.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: ja
#翻译目标语言
to: zh
#huggingface model地址，例如 C:\Users\cai-x\Downloads\pytorch_model.bin
hf_model_path: ""
#devive: cuda, cpu
device: cpu
